// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficAccidentsAPI.Infrastructure.Persistence;

#nullable disable

namespace TrafficAccidentsAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260115023654_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrafficAccidentsAPI.Domain.Entities.Siniestro", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Siniestros", (string)null);
                });

            modelBuilder.Entity("TrafficAccidentsAPI.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Placa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SiniestroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SiniestroId")
                        .HasDatabaseName("IX_Vehiculos_SiniestroId");

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("TrafficAccidentsAPI.Domain.Entities.Victima", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SiniestroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SiniestroId")
                        .HasDatabaseName("IX_Victimas_SiniestroId");

                    b.ToTable("Victimas", (string)null);
                });

            modelBuilder.Entity("TrafficAccidentsAPI.Domain.Entities.Siniestro", b =>
                {
                    b.OwnsOne("TrafficAccidentsAPI.Domain.ValueObjects.FechaHoraSiniestro", "FechaHora", b1 =>
                        {
                            b1.Property<Guid>("SiniestroId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Valor")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaHora");

                            b1.HasKey("SiniestroId");

                            b1.HasIndex("Valor")
                                .HasDatabaseName("IX_Siniestros_FechaHora");

                            b1.ToTable("Siniestros");

                            b1.WithOwner()
                                .HasForeignKey("SiniestroId");
                        });

                    b.OwnsOne("TrafficAccidentsAPI.Domain.ValueObjects.Ubicacion", "Ubicacion", b1 =>
                        {
                            b1.Property<Guid>("SiniestroId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Ciudad");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Departamento");

                            b1.HasKey("SiniestroId");

                            b1.HasIndex("Departamento")
                                .HasDatabaseName("IX_Siniestros_Departamento");

                            b1.ToTable("Siniestros");

                            b1.WithOwner()
                                .HasForeignKey("SiniestroId");
                        });

                    b.Navigation("FechaHora")
                        .IsRequired();

                    b.Navigation("Ubicacion")
                        .IsRequired();
                });

            modelBuilder.Entity("TrafficAccidentsAPI.Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("TrafficAccidentsAPI.Domain.Entities.Siniestro", null)
                        .WithMany("Vehiculos")
                        .HasForeignKey("SiniestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrafficAccidentsAPI.Domain.Entities.Victima", b =>
                {
                    b.HasOne("TrafficAccidentsAPI.Domain.Entities.Siniestro", null)
                        .WithMany("Victimas")
                        .HasForeignKey("SiniestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrafficAccidentsAPI.Domain.Entities.Siniestro", b =>
                {
                    b.Navigation("Vehiculos");

                    b.Navigation("Victimas");
                });
#pragma warning restore 612, 618
        }
    }
}
